[package]
name = "stupid-tap-trick"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { version = "0.32.5", features = ["rand"] }
clap = { version = "4.5.38", features = ["derive"] }
rand = "0.8.5"
